import type { ReactNode } from 'react'

export default function ProductCampaignLayout({ children }: { children: ReactNode }) {
  return <>{children}<style dangerouslySetInnerHTML={{ __html: `
    .campaign-intake-page,.understanding-page,.market-page,.angles-page,.creative-page,.delivery-page{background:var(--soon-ivory)!important;color:var(--soon-ink)!important}
    .campaign-intake-shell,.understanding-shell,.market-shell{width:min(100%,1040px)!important}
    .campaign-progress{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;list-style:none;margin:0 0 30px;padding:0}.campaign-progress li{position:relative;display:flex;align-items:center;gap:8px;color:var(--soon-muted);font-size:.72rem}.campaign-progress li:after{content:'';height:1px;position:absolute;left:calc(100% - 10px);right:-2px;top:14px;background:var(--soon-line)}.campaign-progress li:last-child:after{display:none}.campaign-progress li>span{position:relative;z-index:1;width:28px;height:28px;display:grid;place-items:center;flex:none;border:1px solid var(--soon-line);border-radius:9px;background:var(--soon-ivory);font-size:.65rem;font-weight:800}.campaign-progress li.active{color:var(--soon-oxblood)}.campaign-progress li.active>span{border-color:var(--soon-oxblood);background:var(--soon-oxblood);color:#fff;box-shadow:3px 3px 0 var(--soon-oxblood-dark)}.campaign-progress li.complete>span{border-color:#bed17d;background:#edf6d4;color:var(--soon-success)}
    .production-progress{max-width:1160px;display:grid;grid-template-columns:repeat(4,1fr);gap:8px;list-style:none;margin:0 auto 28px;padding:0}.production-progress li{display:flex;align-items:center;gap:9px;border:1px solid var(--soon-line);border-radius:12px;background:rgba(255,255,255,.58);color:var(--soon-muted);padding:9px 11px;font-size:.7rem}.production-progress li>span{width:30px;height:30px;display:grid;place-items:center;border-radius:9px;background:#eee7e1;color:#796f6a}.production-progress li.active{border-color:var(--soon-oxblood);background:#fff;color:var(--soon-oxblood);box-shadow:var(--soon-shadow-sm)}.production-progress li.active>span{background:var(--soon-oxblood);color:#fff}.production-progress li.complete>span{background:#edf6d4;color:var(--soon-success)}
    .campaign-intake-header span,.understanding-shell header small,.market-shell>header small{color:var(--soon-oxblood)!important;letter-spacing:.11em!important}
    .campaign-intake-header h1,.understanding-shell header h1,.market-shell>header h1{color:var(--soon-ink)!important}
    .campaign-intake-header>button,.understanding-shell>.back,.market-shell>.back{color:var(--soon-muted)!important;font-weight:700!important}
    .campaign-intake-header>button:hover,.understanding-shell>.back:hover,.market-shell>.back:hover{color:var(--soon-oxblood)!important}
    .form-card,.understanding-form>section,.market-summary,.section-block,.sources,.research-state,.error-state{border-color:var(--soon-line)!important;background:var(--soon-paper)!important;box-shadow:none!important}
    .section-title>b{background:var(--soon-oxblood)!important;color:#fff!important;border-radius:10px!important}
    input,textarea,select{accent-color:var(--soon-oxblood)}
    input:focus,textarea:focus,select:focus{border-color:var(--soon-oxblood)!important;box-shadow:var(--soon-focus)!important;outline:0!important}
    .kind-grid button.selected,.choice-list button.selected{border-color:var(--soon-oxblood)!important;background:#f2e9e2!important;color:var(--soon-oxblood)!important}
    .upload-zone{border-color:#ccbdb4!important;background:#fbf8f4!important}
    .upload-zone:hover{border-color:var(--soon-oxblood)!important;background:#fff!important}
    .upload-icon{background:var(--soon-oxblood)!important;box-shadow:4px 4px 0 var(--soon-oxblood-dark)}
    .analyze-button,.form-footer>button,.understanding-form footer button,.market-shell>footer button{background:var(--soon-oxblood)!important;color:#fff!important;box-shadow:4px 4px 0 var(--soon-oxblood-dark)!important}
    .analyze-button:disabled,.form-footer>button:disabled{box-shadow:none!important}
    .add-point-button,.edit-market{color:var(--soon-oxblood)!important;border-color:var(--soon-line)!important}
    .form-footer,.understanding-form footer,.market-shell>footer{border-color:var(--soon-line)!important;background:rgba(255,255,255,.97)!important;color:var(--soon-ink)!important;box-shadow:var(--soon-shadow-md)!important}
    .understanding-form footer button.secondary{background:#fff!important;color:var(--soon-oxblood)!important;border-color:var(--soon-line)!important;box-shadow:none!important}
    .market-summary{border-left:4px solid var(--soon-oxblood)!important}
    .opportunity-grid article:nth-child(1){border-color:#d9b9b1!important;background:#f7eae7!important}
    .opportunity-grid article:nth-child(2){border-color:#c8d8ef!important;background:var(--soon-data-blue)!important}
    .opportunity-grid article:nth-child(3){border-color:#d7e5a7!important;background:#f1f7d9!important}
    .opportunity-grid article:nth-child(1) b{background:var(--soon-oxblood)!important}.opportunity-grid article:nth-child(2) b{background:#4e6fae!important}.opportunity-grid article:nth-child(3) b{background:#607a1c!important}
    .research-state i{border-top-color:var(--soon-oxblood)!important}
    .competitor-messages p span,.section-heading small{color:var(--soon-muted)!important}
    .recommendation{background:#fbf8f4!important;border-color:var(--soon-line)!important}
    .angles-shell,.creative-shell,.delivery-shell{background:var(--soon-ivory)!important}.angles-shell>.back,.creative-shell>.back,.delivery-shell>.back{display:flex;align-items:center;gap:7px;color:var(--soon-muted)!important;font-weight:700}.angles-shell>header small,.creative-shell>header small,.delivery-shell>header small,.pack-head small{color:var(--soon-oxblood)!important}.loading-card,.creative-page .loading,.delivery-page .loading,.angle-card,.plan-intro,.angle-section,.review-overview,.delivery-card,.summary>div{border-color:var(--soon-line)!important;background:#fff!important;box-shadow:none!important}.loading-card i,.creative-page .loading i{border-top-color:var(--soon-oxblood)!important}.recommendation-panel{background:var(--soon-oxblood)!important;box-shadow:7px 7px 0 var(--soon-oxblood-dark)}.recommendation-panel span{color:var(--soon-chartreuse)!important}.recommendation-panel button{background:var(--soon-chartreuse)!important;color:var(--soon-ink)!important}.recommendation-icon{background:#fff!important;color:var(--soon-oxblood)!important}.angle-card.approved{border-color:var(--soon-oxblood)!important;box-shadow:5px 5px 0 #d9bbb5!important}.angle-card blockquote{border-left-color:var(--soon-clay)!important;background:#fbf5f1!important}.angle-top b,.angle-card.approved .angle-top em{background:#f1f7d9!important;color:#536a18!important}.quick-facts span{display:flex;align-items:center;gap:5px}.quick-facts svg,.role-summary svg{color:var(--soon-oxblood)}.rank-label>i{display:grid;place-items:center!important;color:var(--soon-oxblood)!important}.confirm-bar,.creative-page .confirm-bar,.delivery-shell>footer{background:var(--soon-oxblood)!important;box-shadow:7px 7px 0 var(--soon-oxblood-dark)!important}.confirm-bar button,.delivery-shell>footer button{background:var(--soon-chartreuse)!important;color:var(--soon-ink)!important}.angle-letter{background:var(--soon-oxblood)!important;color:#fff!important}.campaign-timeline span.active,.week-tabs button.active,.week-nav button.active{background:var(--soon-oxblood)!important;border-color:var(--soon-oxblood)!important;color:#fff!important}.card-top>span,.meta>span,.review-overview small{color:var(--soon-oxblood)!important}.creative-card,.delivery-card{border-color:var(--soon-line)!important}.creative-card .edit,.detail{color:var(--soon-oxblood)!important;border-color:var(--soon-line)!important;background:#fbf8f4!important}.actions .approve,.detail-panel .approve{background:var(--soon-oxblood)!important;border-color:var(--soon-oxblood)!important}.schedule{background:var(--soon-chartreuse)!important;color:var(--soon-ink)!important}.revision-orb{background:var(--soon-oxblood)!important}.revision-orb span{background:var(--soon-chartreuse)!important}.revision-steps span.active{background:var(--soon-oxblood)!important}.autosave-note,.reference-note{background:#edf6d4!important;color:var(--soon-success)!important}
    .campaign-intake-header>button,.understanding-shell>.back,.market-shell>.back,.analyze-button,.add-point-button,.form-footer>button{display:flex;align-items:center;gap:7px}
    @media(max-width:640px){.form-footer,.understanding-form footer,.market-shell>footer{bottom:10px!important;border-radius:14px!important}.campaign-intake-shell,.understanding-shell,.market-shell{padding-left:16px!important;padding-right:16px!important}.campaign-progress,.production-progress{overflow-x:auto;grid-template-columns:repeat(4,minmax(116px,1fr));padding:2px 2px 8px}}
  `}}/></>
}
