const assert=require('node:assert/strict'),fs=require('node:fs');
const {load}=require('./ts-loader.cjs');
const {compositionKey,resolveComposition,setCompositionMode}=load('lib/composition-mode.ts');
const master=load('lib/content-templates/core-master-template.tsx');
const {optimizeCarouselAssets}=load('lib/optimize-carousel-assets.ts',{'./composition-advice':{compositionAdvice:()=>({action:'extend',reason:'space',placement:{aspectRatio:.8,topFraction:0}})}});
const {renderToStaticMarkup}=require('react-dom/server');
const contract=JSON.parse(fs.readFileSync('tests/fixtures/clear-magazine-v3.contract.json'));
const frame={x:0,y:0,width:1080,height:1350},zones=[{x:30,y:850,width:1000,height:400}];
const key=compositionKey(frame,zones);
assert.equal(key,compositionKey({x:0,y:0,width:540,height:675},zones.map(z=>Object.fromEntries(Object.entries(z).map(([k,v])=>[k,v/2])))));
assert.notEqual(key,compositionKey(frame,[]));
const a={id:'a',url:'original',width:640,height:360,compositionMode:'ai'};
assert.equal(resolveComposition(a,key).compositionFit,'contain','unprepared AI preview never silently crops');
const cached={...a,compositionVariants:{[key]:{sourceUrl:'original',action:'extend',reason:'tested',url:'extended',width:640,height:800,extensionId:'run'}}};
assert.equal(resolveComposition(cached,key).url,'extended');
assert.equal(resolveComposition({...cached,url:'changed'},key).url,'changed','source changes invalidate only matching geometry');
assert.equal(resolveComposition(setCompositionMode([cached],'original')[0],key).url,'original');
assert.equal(resolveComposition(setCompositionMode([cached],'ai')[0],key).url,'extended','switching preserves reusable result');
assert.equal(resolveComposition({...cached,url:'approved-cover',extensionOriginal:{url:'original'}},key).url,'approved-cover');
async function main(){
 const frames=[{assetId:'a',frame,textZones:zones,page:'P.1'},{assetId:'a',frame:{...frame,width:520},textZones:[],page:'P.3'}];
 let calls=0;
 const actions={analyze:async()=>({}),dimensions:async()=>({width:640,height:360}),generate:async()=>({id:'run'+(++calls),originalUrl:'original',url:'extended'+calls,width:640,height:800}),progress:()=>{}};
 const results=await optimizeCarouselAssets([a],frames,actions);
 assert.equal(calls,2);assert.equal(results[0].url,'original');assert.equal(Object.keys(results[0].compositionVariants).length,2);
 await optimizeCarouselAssets(results,frames,actions);assert.equal(calls,2,'refresh and retry reuse geometry results');
 await optimizeCarouselAssets(setCompositionMode([a],'original'),frames,actions);assert.equal(calls,2,'original mode incurs no AI requests');
 const options={design:master.getCoreMasterPageDesign(contract,'end'),copy:{headline:'標題',body:['資料','問題','行動']},page:'06',primary:a,branding:{name:'TEST'},fonts:{family:'Test',editorialFamily:'Test'}};
 const g=master.coreMasterLayoutGeometry({...options,planning:true});
 const actualKey=compositionKey(g.images[0].rect,g.textZones);
 const actual={...a,compositionVariants:{[actualKey]:{sourceUrl:'original',action:'extend',reason:'checked',url:'verified-extension',width:640,height:800,extensionId:'run'}}};
 const html=renderToStaticMarkup(master.renderCoreMasterPage({...options,primary:actual}));
 const editor=master.createCoreMasterCanvas({...options,primary:actual});
 assert.ok(html.includes('verified-extension'));assert.ok(editor.objects.some(o=>o.src==='verified-extension'));
 const safe=master.createCoreMasterCanvas({...options,primary:{...a,compositionMode:'original'}});
 const photo=safe.objects.find(o=>o.type==='Image');assert.equal(photo.height,700);assert.equal(photo.data.editorImageFrame.fit,'contain');
 assert.ok(safe.objects.find(o=>o.data.role==='headline').top>=700,'fallback copy has its own space');
 const context=load('lib/project-style-context.ts',{'./production-style':{object:v=>v&&typeof v==='object'?v:{},fingerprint:JSON.stringify}});
 const p={selected_format:'carousel',production:{assetStatus:'confirmed',assets:[{...a,compositionMode:undefined}]}};
 assert.equal(context.projectStyleContext(p).inputHash,context.projectStyleContext({...p,production:{...p.production,assets:[cached]}}).inputHash,'AI composition must not invalidate style selection');
 console.log('PASS: modes, no AI in original mode, per-slot cache, restored mode reuse, source invalidation, approved cover, preview/editor parity, no-crop fallback, stable style hash');
}
main().catch(e=>{console.error(e);process.exitCode=1});
