const assert=require('node:assert/strict');
const {load}=require('./ts-loader.cjs');
const {copyFieldTargets,copyCandidateRequest,applyCopyCandidates,readCopyCandidates,copyCandidatesSchema,rejectedCopyCandidates}=load('lib/copy-field-candidates.ts');
const long='據報哈佛有研究發現，雪糕與較低的二型糖尿病風險存在關聯，但有關鍵條件';
const page={headline:'研究摘要',subheadline:'',role:'cover',body:[long],assetId:'keep',designDirection:'private layout instructions'};
const targets=copyFieldTargets(page,{});
assert.equal(targets.length,1);assert.equal(targets[0].field,'body.0');assert.equal(targets[0].currentLength,34);assert.equal(targets[0].hardLimit,28);
const request=copyCandidateRequest('existing-model',targets);
assert.ok(!request.messages[0].content.includes('private layout'));assert.ok(!JSON.stringify(copyCandidatesSchema).includes('maxItems'));
const short='據報哈佛研究指雪糕與較低二型糖尿病風險相關，惟有條件';
const result=applyCopyCandidates(page,targets,{fields:[{field:'body.0',candidates:[long,'雪糕可降低糖尿病風險',short]},{field:'headline',candidates:['不應修改']} ]});
assert.equal(result.body[0],short);assert.equal(result.headline,page.headline);assert.equal(result.assetId,'keep');assert.equal(page.body[0],long);
assert.equal(applyCopyCandidates(page,targets,{fields:[{field:'body.0',candidates:['','據報…',long]}]}).body[0],long);
const uncertain={...page,body:['原帖指某研究可能有相關發現，但目前仍未能獨立核實，此說法不代表因果關係']};
const more=copyFieldTargets(uncertain,{});
assert.equal(applyCopyCandidates(uncertain,more,{fields:[{field:'body.0',candidates:['研究已證實有效']}]}).body[0],uncertain.body[0]);
assert.throws(()=>readCopyCandidates({content:[{type:'text',text:'{"fields":[{"field":"body.0","candidates":[1]}]}'}]}));
const comparison={headline:'比較',role:'comparison',body:['Ice Cream','Frozen Dessert','乳脂肪≥10%，以鮮奶油為基礎','以植物油取代鮮奶油','根據原帖引述美國FDA標準，乳脂肪須達10%或以上才可標示為Ice Cream；MFGM相關研究說法暫列為待核實','原帖引述美國FDA標準；MFGM說法暫未能獨立核實']};
const summaryTargets=copyFieldTargets(comparison,{});
assert.equal(summaryTargets.length,1);
assert.ok(!summaryTargets[0].requirements.some(s=>s.includes('因果')));
assert.ok(summaryTargets[0].alreadyVisible.includes(comparison.body[2]));
assert.ok(targets[0].requirements.some(s=>s.includes('因果')));
const bad='原帖指FDA規定Ice Cream乳脂肪須達10%以上；MFGM關聯說法待核實';
const feedback=rejectedCopyCandidates(summaryTargets,{fields:[{field:'body.4',candidates:[bad]}]});
assert.equal(feedback[0].rejected[0].length,39);
assert.ok(feedback[0].rejected[0].reasons[0].includes('超出7字'));
summaryTargets[0].previousRejections=feedback[0].rejected;
assert.ok(copyCandidateRequest('existing-model',summaryTargets).messages[0].content.includes('超出7字'));
const revised='原帖引述分類標準；MFGM說法仍待核實';
assert.equal(applyCopyCandidates(comparison,summaryTargets,{fields:[{field:'body.4',candidates:[revised]}]}).body[4],revised);
assert.equal(applyCopyCandidates(comparison,summaryTargets,{fields:[{field:'body.4',candidates:['分類標準與MFGM研究']}]}).body[4],comparison.body[4]);
const end={headline:'你吃辣是因為喜歡',role:'end',body:['研究不是叫你開始吃辣，也不是叫你停下來。它只是告訴你：在某些人身上、某些條件下，吃辣與更低的死亡風險同時出現過','你吃辣嗎','留言分享']};
const endTargets=copyFieldTargets(end,{});
assert.equal(applyCopyCandidates(end,endTargets,{fields:[{field:'body.0',candidates:['研究不作飲食建議，僅指出在某些人、某些條件下，吃辣與較低死亡風險曾同時出現']}]}).body[0],'研究不作飲食建議，僅指出在某些人、某些條件下，吃辣與較低死亡風險曾同時出現');
const currentEnd={headline:'數字值得參考 但不是吃辣的理由',role:'end',body:['兩份大型研究方向一致，但結論有限：相關不等於因果，吃辣不是長壽的處方。如果你本來就愛吃辣、腸胃也沒問題，這個數字或許讓你安心一點；如果你腸胃敏感，這份研究不是繼續吃辣的理由','你平時吃辣的頻率是多少？','留言告訴我們，或收藏這篇備用']};
const currentTargets=copyFieldTargets(currentEnd,{});
assert.ok(!currentTargets.find(t=>t.field==='body.0').requirements.some(s=>s.includes('可能性')),'conversational 或許 must not become a scientific qualifier');
assert.equal(applyCopyCandidates(currentEnd,currentTargets,{fields:[{field:'body.0',candidates:['研究只顯示相關，不代表因果；吃辣並非長壽處方']},{field:'body.1',candidates:['你平時多久吃一次辣？']},{field:'body.2',candidates:['留言分享，或收藏備用']}]}).body[0],'研究只顯示相關，不代表因果；吃辣並非長壽處方');
console.log('PASS field alternatives: 34-to-28 regression, exact codepoint counts, source/uncertainty guards, no full-page prompt, safe selection');
