const assert=require('node:assert/strict'),fs=require('node:fs'),{load}=require('./ts-loader.cjs');
const {imageStep,imageLatestStep,imageStudioSteps}=load('lib/studio-flow.ts');
assert.equal(imageStudioSteps.length,4);
for(const [old,next] of [['assets','structure'],['drafts','structure'],['style','format'],['carousel','carousel']])assert.equal(imageStep(old),next);
assert.equal(imageLatestStep({stage:'production',selected_format:'carousel',production:{status:'structure_confirmed'}}),'format');
assert.equal(imageLatestStep({stage:'production',selected_format:'carousel',format_decision:{templateCode:'x'},production:{productionStatus:'drafts_ready'}}),'structure');
assert.equal(imageLatestStep({stage:'production',selected_format:'carousel',format_decision:{templateCode:'x'},production:{productionStatus:'images_ready'}}),'carousel');
const contract=JSON.parse(fs.readFileSync('tests/fixtures/clear-magazine-v3.contract.json'));
const style={code:'clear_magazine_carousel',styleId:'style',name:'清晰雜誌',version:{id:'v',number:4,ref:'v4',contentHash:'stylehash',rules:{}},templates:[{templateId:'t',code:'t',version:{number:4,rendererCode:'master',contentHash:'hash',contract}}]};
const production={coreRegistry:async()=>({registryVersion:'r4',styles:[style]}),coreCode:v=>v,creatorCode:v=>v,object:v=>v||{}};
const {catalogStyles,selectCatalogStyle,sameCatalogSelection}=load('lib/core-catalog-selection.ts',{'./production-style':production});
(async()=>{
 assert.equal(catalogStyles([style,{...style,templates:[]}]).length,1);
 const snapshot=await selectCatalogStyle('carousel',style.code,'hash');
 assert.equal(snapshot.selectionMode,'core_catalog');assert.equal(snapshot.recommendationId,null);assert.equal(snapshot.confirmedInputHash,null);
 assert.equal(snapshot.templateContractSnapshot,contract,'exact trusted published contract retained');
 await assert.rejects(()=>selectCatalogStyle('carousel',style.code,'client-forged'),/母版已更新/);
 await assert.rejects(()=>selectCatalogStyle('short_video',style.code,'hash'),/不支援/);
 assert.equal(sameCatalogSelection(snapshot,snapshot,'carousel','carousel'),true);
 assert.equal(sameCatalogSelection(snapshot,snapshot,'single_image','carousel'),false);
 const {masterAssetBrief}=load('lib/master-asset-brief.ts');
 const cover=masterAssetBrief({templateContractSnapshot:contract},{role:'cover'},0,6);
 const body=masterAssetBrief({templateContractSnapshot:contract},{role:'longform'},1,6);
 assert.equal(cover.size,'1024x1536');assert.equal(body.size,'1536x1024');
 assert.ok(cover.instruction.includes('typography zones'));assert.ok(body.instruction.includes('1.714'));
 const source=fs.readFileSync('app/onboarding/content-studio/page.tsx','utf8');
 assert.ok(!source.includes('void prepareStyleCompositions(compositionPreviewSignature);'),'no automatic preview generation');
 console.log('PASS: four-step aliases, resume, trusted catalog snapshots, tamper rejection, exact master and per-slot AI image briefs');
})().catch(e=>{console.error(e);process.exitCode=1});
