const assert=require('node:assert/strict');
const {load}=require('./ts-loader.cjs');
const {editorialStyleAvailability:apply}=load('lib/editorial-style-availability.ts');
const result={id:'existing-run',styles:[],emptyReason:'no match',candidateCount:1};
const input={format:'instagram_carousel',story:[{headline:'研究說法待核實',copyDirection:'原帖未提供來源，不可作確定結論'}],assets:[{url:'https://example.test/photo.png'}]};
const style={code:'clear_magazine_carousel',format:'instagram_carousel',templates:[{version:{rendererCode:'supported'}}]};
const supports=t=>t.version.rendererCode==='supported';
const before=JSON.stringify({result,input,style});
const output=apply(result,input,[style],supports);
assert.equal(output.styles.length,1);
assert.equal(output.id,result.id);
assert.equal(output.styles[0].recommendation.source,'layout_eligibility');
assert.match(output.styles[0].recommendation.reason,/不是資料核實/);
assert.equal(output.emptyReason,'');
assert.equal(JSON.stringify({result,input,style}),before,'must not mutate story, assets or original AI result');
assert.equal(apply(output,input,[style],supports),output,'idempotent cache');
for(const bad of [{...input,format:'human_short_video'},{...input,story:[]},{...input,assets:[]},{...input,story:[{headline:'no detail'}]}]) assert.equal(apply(result,bad,[style],supports),result);
assert.equal(apply(result,input,[],supports),result,'no unpublished fallback');
assert.equal(apply(result,input,[style],()=>false),result,'no unsupported renderer');
console.log('PASS: cached empty result gains published layout only; provenance, warnings, no content mutation, format and renderer guards');
