const assert=require('node:assert/strict'),{load}=require('./ts-loader.cjs');
const m=load('lib/content-templates/core-master-template.tsx');
const contract=require('./fixtures/clear-magazine-v3.contract.json');
const before=JSON.stringify(contract);
const canvas=(role,copy)=>m.createCoreMasterCanvas({design:contract.master_designs[role],copy:{role,...copy},page:'01',branding:{name:'TEST'},fonts:{family:'Brand',editorialFamily:'Brand'}});
const get=(c,role)=>c.objects.find(o=>o.data?.role===role);
const p1=canvas('cover',{headline:'短標題',body:['保留來源的副文']});
assert.ok(get(p1,'subheadline').top<1175,'short headline and subtitle grouped');
assert.equal(get(p1,'page_number').backgroundColor,'#000000B3');
assert.equal(get(p1,'image_credit').backgroundColor,undefined,'no empty credit plate');
const p2=canvas('longform',{headline:'背景介紹',body:['原帖所述背景','','為甚麼會這樣？','資料尚待核實']});
assert.ok(get(p2,'highlight').top<1193,'question follows actual body rather than an empty paragraph');
assert.equal(get(p2,'highlight').fontSize,40);
assert.equal(get(p2,'source').text,'資料尚待核實');
const p3=canvas('split',{headline:'可能原因',body:['第一個有來源的說法','第二個有來源的說法','','來源待核實']});
assert.equal(get(p3,'body_1').fontSize,get(p3,'body_2').fontSize);
assert.ok(get(p3,'body_2').top-get(p3,'body_1').top<257);
const p4=canvas('comparison',{body:['Ice Cream','Frozen Dessert','短說明\n含天然乳脂肪球膜（MFGM）','另一項較長的說明\n含乳化劑及穩定劑'],comparisonLabels:['原料','成分']});
for(let i=1;i<=2;i++)assert.equal(get(p4,`left_row_${i}`).fontSize,get(p4,`right_row_${i}`).fontSize);
assert.ok(!get(p4,'row_rule_0_2'),'no empty third-row decoration');
const three=canvas('comparison',{body:['甲','乙','一\n二\n三','四\n五\n六'],comparisonLabels:['原料','成分','用途']});
assert.equal(get(three,'left_row_3').text,'三','meaningful third row preserved');
assert.equal(JSON.stringify(contract),before,'published master unchanged');
console.log('PASS cover grouping, optional narrative question, split typography, paired comparison sizing, variable row counts, source/master preservation');
