const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const box={exports:{},require:n=>n==='ai'?{}:n==='@ai-sdk/anthropic'?{}:n==='./ai-subject-focus'?{SUBJECT_MODEL:'existing-model'}:require(n)};
vm.runInNewContext(ts.transpileModule(fs.readFileSync('lib/extension-quality.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,box);
const {boundariesSafe,qualityApproved,extensionPrompt}=box.exports;
const edge={safe:true,subjectTouchesEdge:false,environment:'observed mixed shoreline',continuation:'Continue left bank on left and ripples on right'};
const plan={confidence:'high',subjects:'main subject',top:{...edge},bottom:{...edge}};
const geometry={width:640,height:800,originalTop:0,originalHeight:360};
assert.equal(boundariesSafe(plan,geometry),true);
assert.equal(boundariesSafe({...plan,confidence:'medium'},geometry),false);
assert.equal(boundariesSafe({...plan,bottom:{...edge,subjectTouchesEdge:true}},geometry),false);
assert.equal(boundariesSafe({...plan,top:{...edge,safe:false}},geometry),true,'unused edge does not block downward extension');
assert.equal(boundariesSafe({...plan,top:{...edge,safe:false}},{...geometry,originalTop:100}),false);
assert.equal(boundariesSafe(null,geometry),false);
const review={confidence:'high',addedSubject:false,duplicatedSubject:false,unnaturalReflection:false,environmentMatches:true,seamNatural:true,reason:'checked'};
assert.equal(qualityApproved(review),true);
for(const key of ['addedSubject','duplicatedSubject','unnaturalReflection'])assert.equal(qualityApproved({...review,[key]:true}),false);
for(const key of ['environmentMatches','seamNatural'])assert.equal(qualityApproved({...review,[key]:false}),false);
assert.equal(qualityApproved({...review,confidence:'low'}),false);assert.equal(qualityApproved({}),false);
assert.ok(extensionPrompt(geometry,plan).includes(edge.continuation));
console.log('PASS: boundary-specific continuation, subject-edge rejection, uncertainty and post-generation duplicate/seam gates');
