export type VisualStylePreset = {
  id: string
  name: string
  chineseName: string
  previewImage: string
  aiPromptKeywords: string
  lighting: string
  colorGrade: string
  mood: string
  intensity: string
  fileName: string
  title: string
  titleZh: string
  description: string
  color: string
  lutPath: string
  previewPath: string
  thumbPath: string
}

export const visualStyleBeforePath = '/visual-styles/sample/visual-style-before.jpg'

export const visualStylePresets: VisualStylePreset[] = [
  {
    id: 'natural-boost',
    name: 'Natural Boost',
    chineseName: '自然增強',
    previewImage: '/visual-styles/natural-boost.jpg',
    aiPromptKeywords: 'soft natural light, muted tones, minimal, airy, Japanese aesthetic, clean composition, porcelain skin, hazy background',
    lighting: '自然光',
    colorGrade: '真實中性',
    mood: 'natural, clean, minimal, airy',
    intensity: '低',
    fileName: 'NaturalBoost.cube',
    title: 'Natural Boost',
    titleZh: '自然增強',
    description: '保留原相的自然感，同時提升乾淨度、膚色和商品細節。',
    color: '真實中性',
    lutPath: '/visual-styles/reference/NaturalBoost.cube',
    previewPath: '/visual-styles/previews/natural-boost.jpg',
    thumbPath: '/visual-styles/previews/natural-boost-thumb.jpg',
  },
  {
    id: 'magic-hour',
    name: 'Magic Hour',
    chineseName: '魔法時刻',
    previewImage: '/visual-styles/magic-hour.jpg',
    aiPromptKeywords: 'golden hour, warm amber tones, honey backlight, luminous skin, dreamy, romantic, Korean drama aesthetic',
    lighting: '黃昏光',
    colorGrade: '暖色電影',
    mood: 'dreamy, romantic, luminous',
    intensity: '中',
    fileName: 'MagicHour.cube',
    title: 'Magic Hour',
    titleZh: '魔法時刻',
    description: '偏暖、帶少少黃昏感，適合生活方式、餐飲和旅遊內容。',
    color: '暖色電影',
    lutPath: '/visual-styles/reference/MagicHour.cube',
    previewPath: '/visual-styles/previews/magic-hour.jpg',
    thumbPath: '/visual-styles/previews/magic-hour-thumb.jpg',
  },
  {
    id: 'orange-and-blue',
    name: 'Orange And Blue',
    chineseName: '橙藍電影',
    previewImage: '/visual-styles/orange-and-blue.jpg',
    aiPromptKeywords: 'cinematic orange and teal, strong color contrast, warm skin tones, cool teal shadows, crushed blacks, Hollywood grade',
    lighting: '對比光',
    colorGrade: '橙藍',
    mood: 'cinematic, dramatic, commercial',
    intensity: '中高',
    fileName: 'OrangeAndBlue.cube',
    title: 'Orange And Blue',
    titleZh: '橙藍電影',
    description: '用橙色膚色配冷藍陰影，令畫面更有廣告片和電影感。',
    color: '橙藍',
    lutPath: '/visual-styles/reference/OrangeAndBlue.cube',
    previewPath: '/visual-styles/previews/orange-and-blue.jpg',
    thumbPath: '/visual-styles/previews/orange-and-blue-thumb.jpg',
  },
  {
    id: 'long-beach-morning',
    name: 'Long Beach Morning',
    chineseName: '海岸清晨',
    previewImage: '/visual-styles/long-beach-morning.jpg',
    aiPromptKeywords: 'bright overexposed natural light, peachy white tones, lifted shadows, sun-drenched, California morning, lens flare',
    lighting: '早晨光',
    colorGrade: '清爽暖調',
    mood: 'fresh, bright, sun-drenched',
    intensity: '低中',
    fileName: 'LongBeachMorning.cube',
    title: 'Long Beach Morning',
    titleZh: '海岸清晨',
    description: '清爽、明亮、帶一點海邊早晨感，適合輕生活和戶外品牌。',
    color: '清爽暖調',
    lutPath: '/visual-styles/reference/LongBeachMorning.cube',
    previewPath: '/visual-styles/previews/long-beach-morning.jpg',
    thumbPath: '/visual-styles/previews/long-beach-morning-thumb.jpg',
  },
  {
    id: 'cold-chrome',
    name: 'Cold Chrome',
    chineseName: '冷色金屬',
    previewImage: '/visual-styles/cold-chrome.jpg',
    aiPromptKeywords: 'cool blue-grey tones, metallic highlights, clinical contrast, silver white balance, futuristic, tech aesthetic',
    lighting: '冷光',
    colorGrade: '銀藍',
    mood: 'futuristic, clinical, premium tech',
    intensity: '中',
    fileName: 'ColdChrome.cube',
    title: 'Cold Chrome',
    titleZh: '冷色金屬',
    description: '冷調、乾淨、偏科技感，適合產品、軟件和高質感服務。',
    color: '銀藍',
    lutPath: '/visual-styles/reference/ColdChrome.cube',
    previewPath: '/visual-styles/previews/cold-chrome.jpg',
    thumbPath: '/visual-styles/previews/cold-chrome-thumb.jpg',
  },
  {
    id: 'blue-hour',
    name: 'Blue Hour',
    chineseName: '藍調時刻',
    previewImage: '/visual-styles/blue-hour.jpg',
    aiPromptKeywords: 'deep indigo shadows, cobalt blue, warm amber interior light, moody blue hour, European cafe dusk',
    lighting: '低光',
    colorGrade: '深藍',
    mood: 'moody, mature, intimate',
    intensity: '中',
    fileName: 'BlueHour.cube',
    title: 'Blue Hour',
    titleZh: '藍調時刻',
    description: '偏深藍和黃昏氣氛，適合更成熟、安靜、有故事感的品牌。',
    color: '深藍',
    lutPath: '/visual-styles/reference/BlueHour.cube',
    previewPath: '/visual-styles/previews/blue-hour.jpg',
    thumbPath: '/visual-styles/previews/blue-hour-thumb.jpg',
  },
  {
    id: 'blue-architecture',
    name: 'Blue Architecture',
    chineseName: '都市冷藍',
    previewImage: '/visual-styles/blue-architecture.jpg',
    aiPromptKeywords: 'steel blue tones, desaturated, harsh contrast, blue-grey shadows, metropolitan, urban cold',
    lighting: '硬光',
    colorGrade: '建築冷藍',
    mood: 'urban, architectural, precise',
    intensity: '中高',
    fileName: 'BlueArchitecture.cube',
    title: 'Blue Architecture',
    titleZh: '都市冷藍',
    description: '冷峻、建築感、線條感較強，適合空間、設計和城市品牌。',
    color: '建築冷藍',
    lutPath: '/visual-styles/reference/BlueArchitecture.cube',
    previewPath: '/visual-styles/previews/blue-architecture.jpg',
    thumbPath: '/visual-styles/previews/blue-architecture-thumb.jpg',
  },
  {
    id: 'lush-green',
    name: 'Lush Green',
    chineseName: '濃郁綠調',
    previewImage: '/visual-styles/lush-green.jpg',
    aiPromptKeywords: 'rich deep greens, earthy warm tones, boosted natural saturation, dappled light, organic, botanical',
    lighting: '柔和自然光',
    colorGrade: '濃綠',
    mood: 'organic, botanical, fresh',
    intensity: '中',
    fileName: 'LushGreen.cube',
    title: 'Lush Green',
    titleZh: '濃郁綠調',
    description: '強化植物、食材和自然元素，適合健康、餐飲和戶外內容。',
    color: '濃綠',
    lutPath: '/visual-styles/reference/LushGreen.cube',
    previewPath: '/visual-styles/previews/lush-green.jpg',
    thumbPath: '/visual-styles/previews/lush-green-thumb.jpg',
  },
  {
    id: 'crisp-autumn',
    name: 'Crisp Autumn',
    chineseName: '秋日清透',
    previewImage: '/visual-styles/crisp-autumn.jpg',
    aiPromptKeywords: 'warm amber, burnt orange, muted olive, film grain, low autumn light, nostalgic, Japanese autumn',
    lighting: '自然側光',
    colorGrade: '秋日暖調',
    mood: 'nostalgic, warm, tactile',
    intensity: '中',
    fileName: 'CrispAutumn.cube',
    title: 'Crisp Autumn',
    titleZh: '秋日清透',
    description: '帶秋天的暖色和清晰層次，適合服飾、咖啡、生活小物。',
    color: '秋日暖調',
    lutPath: '/visual-styles/reference/CrispAutumn.cube',
    previewPath: '/visual-styles/previews/crisp-autumn.jpg',
    thumbPath: '/visual-styles/previews/crisp-autumn-thumb.jpg',
  },
  {
    id: 'hard-boost',
    name: 'Hard Boost',
    chineseName: '高反差自然',
    previewImage: '/visual-styles/hard-boost.jpg',
    aiPromptKeywords: 'vivid saturation, bold contrast, punchy HDR, energetic, street photography, vibrant urban',
    lighting: '硬光',
    colorGrade: '高飽和',
    mood: 'energetic, punchy, social-first',
    intensity: '高',
    fileName: 'HardBoost.cube',
    title: 'Hard Boost',
    titleZh: '高反差自然',
    description: '提升對比和飽和度，適合需要第一眼更搶眼的社交內容。',
    color: '高飽和',
    lutPath: '/visual-styles/reference/HardBoost.cube',
    previewPath: '/visual-styles/previews/hard-boost.jpg',
    thumbPath: '/visual-styles/previews/hard-boost-thumb.jpg',
  },
  {
    id: 'dark-and-somber',
    name: 'Dark And Somber',
    chineseName: '深沉暗調',
    previewImage: '/visual-styles/dark-and-somber.jpg',
    aiPromptKeywords: 'crushed shadows, low brightness, desaturated brown-black, vignette, cinematic noir, brooding editorial',
    lighting: '低調光',
    colorGrade: '暗調',
    mood: 'brooding, editorial, serious',
    intensity: '高',
    fileName: 'DarkAndSomber.cube',
    title: 'Dark And Somber',
    titleZh: '深沉暗調',
    description: '壓暗、情緒化、對比強，適合高級感、劇情感或更嚴肅題材。',
    color: '暗調',
    lutPath: '/visual-styles/reference/DarkAndSomber.cube',
    previewPath: '/visual-styles/previews/dark-and-somber.jpg',
    thumbPath: '/visual-styles/previews/dark-and-somber-thumb.jpg',
  },
  {
    id: 'soft-black-and-white',
    name: 'Soft Black And White',
    chineseName: '柔和黑白',
    previewImage: '/visual-styles/soft-black-and-white.jpg',
    aiPromptKeywords: 'black and white, high key, soft contrast, smooth skin tones, timeless, minimal monochrome',
    lighting: '柔光',
    colorGrade: '黑白',
    mood: 'timeless, minimal, emotional',
    intensity: '中',
    fileName: 'SoftBlackAndWhite.cube',
    title: 'Soft Black And White',
    titleZh: '柔和黑白',
    description: '去除色彩干擾，集中在人、構圖和情緒，適合品牌故事和人物內容。',
    color: '黑白',
    lutPath: '/visual-styles/reference/SoftBlackAndWhite.cube',
    previewPath: '/visual-styles/previews/soft-black-and-white.jpg',
    thumbPath: '/visual-styles/previews/soft-black-and-white-thumb.jpg',
  },
  {
    id: 'waves',
    name: 'Waves',
    chineseName: '海浪暖調',
    previewImage: '/visual-styles/waves.jpg',
    aiPromptKeywords: 'faded film, lifted shadows, red-orange highlights, desaturated blues, halation, 1980s retro, Lo-Fi',
    lighting: '日光',
    colorGrade: '暖藍綠',
    mood: 'retro, relaxed, summer',
    intensity: '低中',
    fileName: 'Waves.cube',
    title: 'Waves',
    titleZh: '海浪暖調',
    description: '輕微復古和夏日感，適合旅遊、戶外、飲品和年輕生活內容。',
    color: '暖藍綠',
    lutPath: '/visual-styles/reference/Waves.cube',
    previewPath: '/visual-styles/previews/waves.jpg',
    thumbPath: '/visual-styles/previews/waves-thumb.jpg',
  },
  {
    id: 'japanese-film',
    name: 'Japanese Film',
    chineseName: '日系底片',
    previewImage: '/visual-styles/japanese-film.jpg',
    aiPromptKeywords: 'film grain, slightly underexposed, muted desaturated palette, warm midtones, green shadows, halation, Fujifilm analog',
    lighting: 'soft diffused, slightly underexposed',
    colorGrade: 'muted warm midtones, slight green in shadows',
    mood: 'quiet, intimate, analog, nostalgic',
    intensity: 'low',
    fileName: 'JapaneseFilm.cube',
    title: 'Japanese Film',
    titleZh: '日系底片',
    description: '帶底片顆粒、低飽和和安靜日系感，適合細膩、親密、生活化內容。',
    color: 'muted warm midtones, slight green in shadows',
    lutPath: '/visual-styles/reference/JapaneseFilm.cube',
    previewPath: '/visual-styles/japanese-film.jpg',
    thumbPath: '/visual-styles/japanese-film.jpg',
  },
  {
    id: 'korean-drama',
    name: 'Korean Drama',
    chineseName: '韓系清冷',
    previewImage: '/visual-styles/korean-drama.jpg',
    aiPromptKeywords: 'cool toned, teal-green shadows, milky highlights, soft haze, melancholic, Netflix Korean drama palette',
    lighting: 'soft indoor diffused, cool white balance',
    colorGrade: 'teal-green shadows, lifted milky highlights',
    mood: 'melancholic, clean, cinematic',
    intensity: 'low',
    fileName: 'KoreanDrama.cube',
    title: 'Korean Drama',
    titleZh: '韓系清冷',
    description: '清冷柔霧、奶白高光和韓劇式情緒，適合乾淨、克制、電影感內容。',
    color: 'teal-green shadows, lifted milky highlights',
    lutPath: '/visual-styles/reference/KoreanDrama.cube',
    previewPath: '/visual-styles/korean-drama.jpg',
    thumbPath: '/visual-styles/korean-drama.jpg',
  },
]

export function getVisualStylePreset(styleId?: string | null) {
  return visualStylePresets.find((style) => style.id === styleId) || visualStylePresets[0]
}

export default visualStylePresets
