export type VisualStylePreset = {
  id: string
  fileName: string
  title: string
  titleZh: string
  description: string
  lighting: string
  color: string
  intensity: string
  lutPath: string
  previewPath: string
  thumbPath: string
}

export const visualStyleBeforePath = '/visual-styles/sample/visual-style-before.jpg'

export const visualStylePresets: VisualStylePreset[] = [
  {
    id: 'natural-boost',
    fileName: 'NaturalBoost.cube',
    title: 'Natural Boost',
    titleZh: '自然增強',
    description: '保留原相的自然感，同時提升乾淨度、膚色和商品細節。',
    lighting: '自然光',
    color: '真實中性',
    intensity: '低',
    lutPath: '/visual-styles/reference/NaturalBoost.cube',
    previewPath: '/visual-styles/previews/natural-boost.jpg',
    thumbPath: '/visual-styles/previews/natural-boost-thumb.jpg',
  },
  {
    id: 'magic-hour',
    fileName: 'MagicHour.cube',
    title: 'Magic Hour',
    titleZh: '魔法時刻',
    description: '偏暖、帶少少黃昏感，適合生活方式、餐飲和旅遊內容。',
    lighting: '黃昏光',
    color: '暖色電影',
    intensity: '中',
    lutPath: '/visual-styles/reference/MagicHour.cube',
    previewPath: '/visual-styles/previews/magic-hour.jpg',
    thumbPath: '/visual-styles/previews/magic-hour-thumb.jpg',
  },
  {
    id: 'orange-and-blue',
    fileName: 'OrangeAndBlue.cube',
    title: 'Orange And Blue',
    titleZh: '橙藍電影',
    description: '用橙色膚色配冷藍陰影，令畫面更有廣告片和電影感。',
    lighting: '對比光',
    color: '橙藍',
    intensity: '中高',
    lutPath: '/visual-styles/reference/OrangeAndBlue.cube',
    previewPath: '/visual-styles/previews/orange-and-blue.jpg',
    thumbPath: '/visual-styles/previews/orange-and-blue-thumb.jpg',
  },
  {
    id: 'long-beach-morning',
    fileName: 'LongBeachMorning.cube',
    title: 'Long Beach Morning',
    titleZh: '海岸清晨',
    description: '清爽、明亮、帶一點海邊早晨感，適合輕生活和戶外品牌。',
    lighting: '早晨光',
    color: '清爽暖調',
    intensity: '低中',
    lutPath: '/visual-styles/reference/LongBeachMorning.cube',
    previewPath: '/visual-styles/previews/long-beach-morning.jpg',
    thumbPath: '/visual-styles/previews/long-beach-morning-thumb.jpg',
  },
  {
    id: 'cold-chrome',
    fileName: 'ColdChrome.cube',
    title: 'Cold Chrome',
    titleZh: '冷色金屬',
    description: '冷調、乾淨、偏科技感，適合產品、軟件和高質感服務。',
    lighting: '冷光',
    color: '銀藍',
    intensity: '中',
    lutPath: '/visual-styles/reference/ColdChrome.cube',
    previewPath: '/visual-styles/previews/cold-chrome.jpg',
    thumbPath: '/visual-styles/previews/cold-chrome-thumb.jpg',
  },
  {
    id: 'blue-hour',
    fileName: 'BlueHour.cube',
    title: 'Blue Hour',
    titleZh: '藍調時刻',
    description: '偏深藍和黃昏氣氛，適合更成熟、安靜、有故事感的品牌。',
    lighting: '低光',
    color: '深藍',
    intensity: '中',
    lutPath: '/visual-styles/reference/BlueHour.cube',
    previewPath: '/visual-styles/previews/blue-hour.jpg',
    thumbPath: '/visual-styles/previews/blue-hour-thumb.jpg',
  },
  {
    id: 'blue-architecture',
    fileName: 'BlueArchitecture.cube',
    title: 'Blue Architecture',
    titleZh: '都市冷藍',
    description: '冷峻、建築感、線條感較強，適合空間、設計和城市品牌。',
    lighting: '硬光',
    color: '建築冷藍',
    intensity: '中高',
    lutPath: '/visual-styles/reference/BlueArchitecture.cube',
    previewPath: '/visual-styles/previews/blue-architecture.jpg',
    thumbPath: '/visual-styles/previews/blue-architecture-thumb.jpg',
  },
  {
    id: 'lush-green',
    fileName: 'LushGreen.cube',
    title: 'Lush Green',
    titleZh: '濃郁綠調',
    description: '強化植物、食材和自然元素，適合健康、餐飲和戶外內容。',
    lighting: '柔和自然光',
    color: '濃綠',
    intensity: '中',
    lutPath: '/visual-styles/reference/LushGreen.cube',
    previewPath: '/visual-styles/previews/lush-green.jpg',
    thumbPath: '/visual-styles/previews/lush-green-thumb.jpg',
  },
  {
    id: 'crisp-autumn',
    fileName: 'CrispAutumn.cube',
    title: 'Crisp Autumn',
    titleZh: '秋日清透',
    description: '帶秋天的暖色和清晰層次，適合服飾、咖啡、生活小物。',
    lighting: '自然側光',
    color: '秋日暖調',
    intensity: '中',
    lutPath: '/visual-styles/reference/CrispAutumn.cube',
    previewPath: '/visual-styles/previews/crisp-autumn.jpg',
    thumbPath: '/visual-styles/previews/crisp-autumn-thumb.jpg',
  },
  {
    id: 'hard-boost',
    fileName: 'HardBoost.cube',
    title: 'Hard Boost',
    titleZh: '高反差自然',
    description: '提升對比和飽和度，適合需要第一眼更搶眼的社交內容。',
    lighting: '硬光',
    color: '高飽和',
    intensity: '高',
    lutPath: '/visual-styles/reference/HardBoost.cube',
    previewPath: '/visual-styles/previews/hard-boost.jpg',
    thumbPath: '/visual-styles/previews/hard-boost-thumb.jpg',
  },
  {
    id: 'dark-and-somber',
    fileName: 'DarkAndSomber.cube',
    title: 'Dark And Somber',
    titleZh: '深沉暗調',
    description: '壓暗、情緒化、對比強，適合高級感、劇情感或更嚴肅題材。',
    lighting: '低調光',
    color: '暗調',
    intensity: '高',
    lutPath: '/visual-styles/reference/DarkAndSomber.cube',
    previewPath: '/visual-styles/previews/dark-and-somber.jpg',
    thumbPath: '/visual-styles/previews/dark-and-somber-thumb.jpg',
  },
  {
    id: 'soft-black-and-white',
    fileName: 'SoftBlackAndWhite.cube',
    title: 'Soft Black And White',
    titleZh: '柔和黑白',
    description: '去除色彩干擾，集中在人、構圖和情緒，適合品牌故事和人物內容。',
    lighting: '柔光',
    color: '黑白',
    intensity: '中',
    lutPath: '/visual-styles/reference/SoftBlackAndWhite.cube',
    previewPath: '/visual-styles/previews/soft-black-and-white.jpg',
    thumbPath: '/visual-styles/previews/soft-black-and-white-thumb.jpg',
  },
  {
    id: 'waves',
    fileName: 'Waves.cube',
    title: 'Waves',
    titleZh: '海浪暖調',
    description: '輕微復古和夏日感，適合旅遊、戶外、飲品和年輕生活內容。',
    lighting: '日光',
    color: '暖藍綠',
    intensity: '低中',
    lutPath: '/visual-styles/reference/Waves.cube',
    previewPath: '/visual-styles/previews/waves.jpg',
    thumbPath: '/visual-styles/previews/waves-thumb.jpg',
  },
]

export function getVisualStylePreset(styleId?: string | null) {
  return visualStylePresets.find((style) => style.id === styleId) || visualStylePresets[0]
}
