import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import { createServerSupabase } from '@/lib/server-supabase'
import { getWorkspaceAccess } from '@/lib/workspace-access'

const INDUSTRIES = ['food_beverage','travel_experience','sports_wellness','home_living','medical_aesthetics_wellness','beauty_cosmetics','trend_culture'] as const
const list = (value: unknown, max = 8) => Array.isArray(value) ? [...new Set(value.map(String).map((v) => v.trim()).filter(Boolean))].slice(0,max) : []
async function access(request: Request) {
  const server = createServerSupabase(await cookies()); const { data: { user } } = await server.auth.getUser(); if (!user) return null
  const url = new URL(request.url); const body = request.method === 'PATCH' ? await request.clone().json().catch(() => ({})) : {}
  const workspaceId = url.searchParams.get('workspaceId') || String(body.workspaceId || ''); if (!workspaceId) return null
  const workspace = await getWorkspaceAccess({ userId: user.id, email: user.email, workspaceId }); return workspace ? { user, workspaceId, workspace, body } : null
}
async function syncCore(workspaceId: string, profile: Record<string, unknown>) {
  const key=process.env.SOON_CORE_BUNDLE_KEY||process.env.SOON_CORE_KNOWLEDGE_KEY; if(!key||profile.profile_status!=='confirmed') return {synced:false,reason:'not_confirmed_or_key_missing'}
  const response=await fetch(`${(process.env.SOON_CORE_URL||'https://soon-core.vercel.app').replace(/\/$/,'')}/api/intelligence/dna/sync`,{method:'POST',headers:{'content-type':'application/json','x-soon-knowledge-key':key},cache:'no-store',body:JSON.stringify({sourceSystem:'soon-brand',entityType:'client',externalWorkspaceId:workspaceId,primaryIndustryCode:profile.primary_industry_code,secondaryIndustryCodes:profile.secondary_industry_codes,objectives:profile.campaign_objectives,preferredFormats:profile.preferred_formats,profileStatus:profile.profile_status,profileVersion:profile.profile_version})}); if(!response.ok) throw new Error(`Core DNA sync returned ${response.status}`); return {synced:true}
}
export async function GET(request: Request) { const ctx=await access(request); if(!ctx) return NextResponse.json({error:'Unauthorized or workspace missing'},{status:401}); const {data,error}=await ctx.workspace.admin.from('client_dna_profiles').select('*').eq('workspace_id',ctx.workspaceId).maybeSingle(); if(error)return NextResponse.json({error:'未能載入 Client DNA'},{status:500}); return NextResponse.json({profile:data,industryCodes:INDUSTRIES}) }
export async function PATCH(request: Request) { const ctx=await access(request); if(!ctx)return NextResponse.json({error:'Unauthorized or workspace missing'},{status:401}); if(!ctx.workspace.canManageWorkspace)return NextResponse.json({error:'Forbidden'},{status:403}); const body=ctx.body as Record<string,unknown>; const primary=String(body.primaryIndustryCode||''); const secondary=list(body.secondaryIndustryCodes,2).filter(c=>c!==primary); if(!INDUSTRIES.includes(primary as typeof INDUSTRIES[number])||secondary.some(c=>!INDUSTRIES.includes(c as typeof INDUSTRIES[number])))return NextResponse.json({error:'行業分類不正確'},{status:422}); const {data:existing}=await ctx.workspace.admin.from('client_dna_profiles').select('*').eq('workspace_id',ctx.workspaceId).maybeSingle(); const confirmed=body.confirm===true; const row={workspace_id:ctx.workspaceId,primary_industry_code:primary,secondary_industry_codes:secondary,campaign_objectives:'campaignObjectives' in body?list(body.campaignObjectives):existing?.campaign_objectives??[],audience_summary:'audienceSummary' in body?String(body.audienceSummary||'').trim()||null:existing?.audience_summary??null,brand_tone:'brandTone' in body?list(body.brandTone):existing?.brand_tone??[],preferred_formats:'preferredFormats' in body?list(body.preferredFormats):existing?.preferred_formats??[],restrictions:'restrictions' in body?list(body.restrictions):existing?.restrictions??[],profile_status:confirmed?'confirmed':'draft',profile_version:Number(existing?.profile_version||0)+1,confirmed_by:confirmed?ctx.user.id:null,confirmed_at:confirmed?new Date().toISOString():null,updated_at:new Date().toISOString()}; const {data,error}=await ctx.workspace.admin.from('client_dna_profiles').upsert(row).select('*').single(); if(error)return NextResponse.json({error:'未能儲存 Client DNA'},{status:500}); try{return NextResponse.json({profile:data,core:await syncCore(ctx.workspaceId,data)})}catch(error){return NextResponse.json({profile:data,core:{synced:false,reason:String(error)},warning:'分類已儲存，但 Core 暫時未同步'})} }
