'use client'

import { useCallback, useEffect, useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { DashboardSidebar, dashboardSidebarStyles } from '@/components/dashboard/DashboardSidebar'
import { SoonIcon } from '@/components/ui/SoonIcon'
import { resolveActiveWorkspace, WORKSPACE_CHANGED_EVENT } from '@/lib/workspace-client'

type Campaign = { id:string; name:string; status?:string; imageUrl?:string|null; product?:{name?:string}|Array<{name?:string}>|null; progress:{pendingApproval:number;changesRequested:number;weeks:Record<string,{total:number;ready:number;approved:number;pendingApproval:number;changesRequested:number}>} }
type ContentProject = { id:string; title:string; selected_format?:string|null; stage:string; production?:{approvalStatus?:string;captionDraft?:string;generatedPages?:Array<{page?:string;url?:string}>}; updated_at?:string }

function nameOf(campaign: Campaign) { const product=Array.isArray(campaign.product)?campaign.product[0]:campaign.product; return product?.name||campaign.name.replace(/ Campaign$/i,'') }

export default function ContentReviewPage() {
  const router=useRouter(); const searchParams=useSearchParams(); const highlightedProject=searchParams.get('project')
  const [workspaceId,setWorkspaceId]=useState(''); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [projects,setProjects]=useState<ContentProject[]>([])
  const [loading,setLoading]=useState(true); const [reviewingId,setReviewingId]=useState(''); const [error,setError]=useState('')
  const load=useCallback(async()=>{setLoading(true);setError('');try{const resolved=await resolveActiveWorkspace();if(!resolved.workspaceId)throw new Error('找不到目前工作台');setWorkspaceId(resolved.workspaceId);const[campaignResponse,projectResponse]=await Promise.all([fetch(`/api/product-campaigns?workspaceId=${encodeURIComponent(resolved.workspaceId)}`,{cache:'no-store'}),fetch(`/api/content-projects?workspaceId=${encodeURIComponent(resolved.workspaceId)}`,{cache:'no-store'})]);const[campaignPayload,projectPayload]=await Promise.all([campaignResponse.json().catch(()=>({})),projectResponse.json().catch(()=>({}))]);if(!campaignResponse.ok)throw new Error(campaignPayload.detail||campaignPayload.error||'未能載入宣傳活動審批');if(!projectResponse.ok)throw new Error(projectPayload.detail||projectPayload.error||'未能載入內容審批');setCampaigns(Array.isArray(campaignPayload.campaigns)?campaignPayload.campaigns:[]);setProjects(Array.isArray(projectPayload.projects)?projectPayload.projects:[])}catch(loadError){setError(loadError instanceof Error?loadError.message:'未能載入審批內容')}finally{setLoading(false)}},[])
  useEffect(()=>{void load();const reload=()=>void load();window.addEventListener(WORKSPACE_CHANGED_EVENT,reload);return()=>window.removeEventListener(WORKSPACE_CHANGED_EVENT,reload)},[load])
  const projectQueue=useMemo(()=>projects.filter(project=>project.stage==='approval'&&project.production?.approvalStatus==='pending'),[projects])
  const campaignQueue=useMemo(()=>campaigns.filter(campaign=>campaign.status!=='archived').flatMap(campaign=>Object.entries(campaign.progress.weeks).flatMap(([week,progress])=>{const pending=progress.pendingApproval||0;if(!pending&&!progress.changesRequested)return[];return[{campaign,week:Number(week),pending,changes:progress.changesRequested}]})).sort((a,b)=>a.week-b.week),[campaigns])
  const pendingTotal=projectQueue.length+campaignQueue.reduce((sum,item)=>sum+item.pending,0);const changesTotal=campaignQueue.reduce((sum,item)=>sum+item.changes,0)
  async function reviewProject(project:ContentProject,decision:'approved'|'changes_requested'){if(!workspaceId||reviewingId)return;const note=decision==='changes_requested'?window.prompt('請輸入需要修改的內容：')?.trim():'';if(decision==='changes_requested'&&!note)return;setReviewingId(project.id);setError('');try{const response=await fetch('/api/content-projects/approve',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({workspaceId,projectId:project.id,decision,note})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.detail||payload.error||'未能儲存審批決定');await load()}catch(reviewError){setError(reviewError instanceof Error?reviewError.message:'未能儲存審批決定')}finally{setReviewingId('')}}
  const empty=!projectQueue.length&&!campaignQueue.length
  return <main className="content-review-page"><DashboardSidebar activeItem="內容審批"/><section className="content-review-shell">
    <header><small>內容審批</small><h1>{loading?'正在整理待審批內容':pendingTotal?`${pendingTotal} 項內容等待你確認`:changesTotal?`${changesTotal} 項內容正在修改`:'審批已完成'}</h1><p>內容製作及宣傳活動會集中顯示在這裡；你的決定會自動保存。</p></header>
    {loading?<div className="review-state"><i/><strong>正在整理待審批內容…</strong></div>:error?<div className="review-error"><strong>{error}</strong><button onClick={()=>void load()} type="button">重新載入</button></div>:empty?<div className="review-empty"><span><SoonIcon name="check" size={28}/></span><h2>目前沒有待審批內容</h2><p>Step 7 提交後，內容會自動出現在這裡。</p><button onClick={()=>router.push('/onboarding/content-studio')} type="button">前往內容製作</button></div>:<>
      {projectQueue.length?<section className="project-review-queue" aria-label="內容製作審批"><h2>內容製作</h2>{projectQueue.map(project=>{const image=project.production?.generatedPages?.[0]?.url;return <article key={project.id} className={highlightedProject===project.id?'highlighted':''}>{image?<img src={image} alt=""/>:<span className="project-placeholder"><SoonIcon name="image" size={24}/></span>}<div><small>{project.selected_format==='carousel'?'輪播貼文':project.selected_format==='single_image'?'單張圖片':'內容項目'}</small><h3>{project.title}</h3><p>{project.production?.captionDraft||'尚未提供 Caption'}</p></div><div className="project-review-actions"><button className="secondary" onClick={()=>router.push(`/onboarding/content-studio?project=${encodeURIComponent(project.id)}&step=carousel`)} type="button">查看內容</button><button className="changes" disabled={reviewingId===project.id} onClick={()=>void reviewProject(project,'changes_requested')} type="button">要求修改</button><button disabled={reviewingId===project.id} onClick={()=>void reviewProject(project,'approved')} type="button">{reviewingId===project.id?'儲存中…':'批准內容'}</button></div></article>})}</section>:null}
      {campaignQueue.length?<section className="review-queue"><h2>宣傳活動</h2>{campaignQueue.map(({campaign,week,pending,changes})=><article key={`${campaign.id}-${week}`}><div className="review-campaign">{campaign.imageUrl?<img src={campaign.imageUrl} alt=""/>:<span><SoonIcon name="campaign" size={22}/></span>}<div><small>WEEK {week}</small><h2>{nameOf(campaign)}</h2><p>{pending?`${pending} 項待審批`:''}{pending&&changes?' · ':''}{changes?`${changes} 項正在修改`:''}</p></div></div><div className="review-counts">{pending?<span className="pending"><i/>{pending} 待審批</span>:null}{changes?<span><SoonIcon name="edit" size={14}/>{changes} 修改中</span>:null}</div><button onClick={()=>router.push(`/onboarding/product-campaign/${campaign.id}/delivery?week=${week}`)} type="button">{pending?'開始審批':'查看修改進度'}<SoonIcon name="arrow-right" size={16}/></button></article>)}</section>:null}
    </>}
  </section><style jsx global>{`${dashboardSidebarStyles}
    .content-review-page{min-height:100vh;display:grid;grid-template-columns:260px minmax(0,1fr);background:var(--soon-ivory);color:var(--soon-ink)}.content-review-shell{width:min(1040px,calc(100% - 56px));margin:0 auto;padding:58px 0 90px}.content-review-shell>header{margin-bottom:28px}.content-review-shell>header small{color:var(--soon-oxblood);font-size:.72rem;font-weight:850;letter-spacing:.12em}.content-review-shell>header h1{margin:8px 0 6px;font-size:clamp(2rem,4vw,3.1rem);letter-spacing:-.045em}.content-review-shell>header p{margin:0;color:var(--soon-muted)}
    .project-review-queue,.review-queue{display:grid;gap:11px;margin-bottom:28px}.project-review-queue>h2,.review-queue>h2{margin:0 0 4px;font-size:1rem}.project-review-queue>article{display:grid;grid-template-columns:118px minmax(0,1fr) auto;align-items:center;gap:18px;border:1px solid var(--soon-line);border-radius:18px;background:#fff;padding:14px}.project-review-queue>article.highlighted{border-color:var(--soon-oxblood);box-shadow:0 0 0 2px rgba(107,44,48,.12)}.project-review-queue img,.project-placeholder{width:118px;aspect-ratio:4/5;border-radius:11px;background:#eeeae6;object-fit:cover}.project-placeholder{display:grid;place-items:center}.project-review-queue small{color:var(--soon-oxblood);font-size:.65rem;font-weight:850}.project-review-queue h3{margin:5px 0;font-size:1.05rem}.project-review-queue p{display:-webkit-box;overflow:hidden;margin:0;color:var(--soon-muted);font-size:.75rem;line-height:1.45;-webkit-box-orient:vertical;-webkit-line-clamp:2}.project-review-actions{display:grid;gap:7px}.project-review-actions button{min-width:100px;border:0;border-radius:9px;background:var(--soon-oxblood);color:#fff;padding:10px 12px;font:inherit;font-size:.72rem;font-weight:850;cursor:pointer}.project-review-actions button.secondary{border:1px solid var(--soon-line);background:#fff!important;color:var(--soon-ink)!important}.project-review-actions button.changes{background:#eeeae6;color:var(--soon-oxblood)}.project-review-actions button:disabled{opacity:.45}
    .review-queue>article{display:grid;grid-template-columns:1fr auto auto;align-items:center;gap:24px;border:1px solid var(--soon-line);border-radius:18px;background:#fff;padding:17px}.review-campaign{display:flex;align-items:center;gap:14px;min-width:0}.review-campaign>img,.review-campaign>span{width:66px;height:66px;flex:none;border:1px solid var(--soon-line);border-radius:13px;background:#f2ece6;object-fit:contain}.review-campaign>span{display:grid;place-items:center;color:var(--soon-oxblood)}.review-campaign small{color:var(--soon-oxblood);font-size:.65rem;font-weight:850}.review-campaign h2{margin:4px 0 2px;font-size:1.08rem}.review-campaign p{margin:0;color:var(--soon-muted);font-size:.75rem}.review-counts{display:flex;gap:7px}.review-counts span{display:flex;align-items:center;gap:6px;border-radius:999px;background:#eeeae6;color:var(--soon-copy);padding:7px 10px;font-size:.7rem;font-weight:800}.review-counts span.pending{background:#ffe7e5;color:#ad3030}.review-counts i{width:7px;height:7px;border-radius:50%;background:var(--soon-danger)}.review-queue>article>button,.review-empty button{display:flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:11px;background:var(--soon-oxblood);color:#fff;padding:12px 15px;font:inherit;font-size:.78rem;font-weight:850;cursor:pointer}
    .review-state,.review-empty,.review-error{min-height:320px;display:grid;place-items:center;align-content:center;gap:12px;border:1px dashed var(--soon-line);border-radius:18px;background:rgba(255,255,255,.55);text-align:center}.review-state i{width:28px;height:28px;border:3px solid #eadfd8;border-top-color:var(--soon-oxblood);border-radius:50%;animation:reviewSpin .8s linear infinite}.review-error button{border:1px solid var(--soon-line);border-radius:9px;background:#fff;padding:9px 12px}.review-empty>span{width:58px;height:58px;display:grid;place-items:center;border-radius:16px;background:#edf6d4;color:var(--soon-success)}.review-empty h2{margin:4px 0 0}.review-empty p{margin:0 0 5px;color:var(--soon-muted)}@keyframes reviewSpin{to{transform:rotate(360deg)}}
    @media(max-width:980px){.content-review-page{display:block}.content-review-shell{width:min(100% - 28px,760px);padding:34px 0 70px}.project-review-queue>article,.review-queue>article{grid-template-columns:1fr}.project-review-queue img,.project-placeholder{width:100%;max-height:300px}.project-review-actions{grid-template-columns:repeat(3,1fr)}.review-queue>article>button{width:100%}.review-counts{margin-left:80px}}@media(max-width:520px){.project-review-actions{grid-template-columns:1fr}.review-counts{margin-left:0}.review-counts span{flex:1;justify-content:center}}
  `}</style></main>
}
